### ISSUE TITLE
leaked secrets

### ISSUE THREAD

**Issue by 0xdarkman** [fabriken/py-binance-SMA-trader#3]
check the history:
https://github.com/fabriken/py-binance-SMA-trader/commit/655eca76a5249b90ff9a420f7840af32d6d41709#diff-117426151e93a626f8b46bfdb3a95b3f4a62e5f4dd6e65975a7c50759bf04482

**Comment by fabriken** [comment]
All good, it was an old key. No harm done. Thanks for being attentive though!
